### ISSUE TITLE
_Ds_store file should be gitignored.

### ISSUE THREAD

**Issue by BOVAGE** [khawajaazfar2000/Hacktoberfest2022-Repository-4#20]
There is need for .gitignore file inorder to avoid committing files that do not need to be tracked by git.

**Comment by khawajaazfar** [comment]
Go ahead

**Comment by BOVAGE** [comment]
Okay. Kindly assign this to me

**Comment by DipeshRaval** [comment]
please see my pr and merge it bcz there is problem in return index
